### PR TITLE
changes to the info/rules interface

### PR DESCRIPTION
**Pull request by cp-codes2**
added some spacing between lines so it does not look like a giant wall of text as much

### CODE REVIEW

**Comment by BlankParenthesis** [comment]
The adding of paragraphs to each item is semantically questionable, complicates the DOM, and - in the case of contained sub-lists - is incorrect. 

This would probably be better implemented in CSS which is the appropriate place to implement purely visual changes such as this. This could be as a general change to the display of ordered list items or using a class.

**Review by FlyingSixtySix — CHANGES_REQUESTED** [review]
I agree with @BlankParenthesis; with the goal of this being added spacing (as far as I understand), it would be more efficient to handle it via CSS than more elements.

**Comment by cp-codes2** [comment]
Will do. Haven't had much time to work on this lately but shouldn’t take long

**Comment by FlyingSixtySix** [comment]
Closed due to inactivity.

**Pull request closed without merging**
