### PR TITLE
Added new theme "Terminal"

### PR DESCRIPTION
**Pull request by SoftwareKitten**
Darker + green theme built off of matte

### CODE REVIEW

**Comment by cp-codes2** [comment]
looks really good to me
couple things I noticed though are the dark green text blending in with black at some places like 
Screen Shot 2020-11-18 at 10 57 36 AM
Screen Shot 2020-11-18 at 11 00 45 AM

and maybe the border around palette colors 
Screen Shot 2020-11-18 at 10 59 17 AM

other than I that I think its pretty much ready to go
nice work

**Comment by SoftwareKitten** [comment]
I made those dark green on purpose
having it all light green kinda looked bad, I wanted to break it up a bit

**Comment by netux** [comment]
I agree with CP. Some dark green text is unreadable for some (including me).

Since you don't like light green, may I suggest using white maybe?

**Comment by SoftwareKitten** [comment]
hmm
mabye i can make it slightly lighter

**Comment by SoftwareKitten** [comment]
there we go... it is lighter, but not as light as the rest of the light green
i also made the panel close button lighter... because I realized that was bugging me that i couldnt see it well... hope that is good!

**Comment by SoftwareKitten** [comment]
hmmm only thing i would want to change... which i don't think I CAN change... is to make the flashing "|" typing indicator a flashing underscore
but I don't think I can change that with css

**Comment by netux** [comment]
The color for toggled checkmarks is very dark in contrast with the background, almost invisible.
image

You still preserve the slider tick color from the Matte theme. Is this intentional?
image

The palette borders still look weird to me
image


Overall it's a nice theme, though the contrast is awful.
I get that that's the point, but I wouldn't use it too much 😅.

**Comment by SoftwareKitten** [comment]
its terminal
huh... i thought i fixxed the slider... hmmmmmmm.... yeah i fix checkboxes in a sec
i tried to make black background a very dark green..... so idk what you meany by contrast is aweful... its just a dark mode with cool green accents

**Comment by SoftwareKitten** [comment]
i copy pasted the text file into my inspect element and slider is green
mabye i messed up in github hold on

**Comment by SoftwareKitten** [comment]
no it shouldn't still be matte theme

**Comment by SoftwareKitten** [comment]
changed palette border colors
this is the final change (unless find something else after its released)

**Pull request merged**
