### PR TITLE
Add new Red theme

### PR DESCRIPTION
**Pull request by pogtato**

### CODE REVIEW

**Review by cp-codes2 — CHANGES_REQUESTED** [review]
nice work on this, a couple things I noticed though is the ping color doesn't seem to contrast well in chat. this could make it hard to notice pings when you are the receiver. 
Screen Shot 2020-12-11 at 11 55 03 AM
also contrast between odd and even messages is a bit high imo.
Screen Shot 2020-12-11 at 11 56 41 AM
  it might look better to make them closer together in color. (perhaps making the light color a bit darker...?) overall nice theme. I look forward to seeing it merged.

**Comment by pogtato** [comment]
> nice work on this, a couple things I noticed though is the ping color doesn't seem to contrast well in chat. this could make it hard to notice pings when you are the receiver.
> Screen Shot 2020-12-11 at 11 55 03 AM
> also contrast between odd and even messages is a bit high imo.
> Screen Shot 2020-12-11 at 11 56 41 AM
> it might look better to make them closer together in color. (perhaps making the light color a bit darker...?) overall nice theme. I look forward to seeing it merged.

I've decreased contrast between odd and even messages
image
And made pings more noticeable
image

**Review by cp-codes2 — APPROVED** [review]
\o/ nice, looking good

**Comment by TheNewKing-001** [comment]
I agree pog this is rly cool

**Pull request merged**
